version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/UFSurfClubWebDev/TDD-Assignment1
    steps:
      - checkout
      - run: npm install
      - run: npm test
