version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/UFSurfClubWebDev/TDD-Assignment1
    steps:
      - checkout
      - run: npm install
      - run: npm test

  workflows:
  matrix-tests:
    jobs:
      - node/test:
          version: 13.11.0
      - node/test:
          version: 12.16.0
      - node/test:
          version: 10.19.0
