version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - run: npm install
      - run: 
          command: npm start
          background: true
      - run: npm test
