version: 2.1

orbs:
  node: circleci/node@3.0.1

jobs:
  build:
    working_directory: TDD-Assignment1/
    executor: node/default
    steps:
      - checkout
      - node/install-npm
      - node/install-packages:
          app-dir: TDD-Assignment1/
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    docker:
      - image: cimg/node:current
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: npm test
